resources:
  - app-namespaces.yaml
  - postgres-secrets.yaml
  - postgres-pvc.yaml
  - cross-ns-forwarding.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - worker-deployment.yaml
  - result-deployment.yaml
  - vote-deployment.yaml
  - vote-ingress.yaml
  - redis-network-policy.yaml
  - postgres-network-policy.yaml
  - https://docs.projectcalico.org/manifests/calico.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.14.0/deploy/static/provider/kind/deploy.yaml
