apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: frontend-ns
  labels:
    app: result-nodejs

spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-nodejs
  template:
    metadata:
      labels:
        app: result-nodejs
    spec:
      containers:
        - name: result
          image: saifmohamed123/result-node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: result-nodejs
  namespace: frontend-ns
spec:
  selector:
    app: result-nodejs
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
