apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  namespace: frontend-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
    - host: vote.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-flask
                port:
                  number: 8080

    - host: result.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: result-nodejs
                port:
                  number: 4000
