name: Result CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "result/"
jobs:
  result-build-push-deploy:
    runs-on: self-hosted

    steps:
      # host runner repo clone 
      - name: Checkout repository
        uses: actions/checkout@v4
      # docker login 
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # build the worker image 
      - name: result image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/result-node:latest -f result/Dockerfile result # the context ( the directory that the docker daemon will work on ) 
     
      - name: Pushing image to the hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/result-node:latest
        # Re-deploy ( rollout ) the updated image for the targeted deployment pods 
      - name: result deployment rollout 
        run: kubectl rollout restart deployment ${{ vars.RESULT_DEPLOYMENT_NAME }} -n ${{ vars.FRONTEND_NAMESPACE }}
          
            











      
