name: Vote CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "vote/"
jobs:
  vote-build-push-deploy:
    runs-on: self-hosted

    steps:
      # host runner repo clone 
      - name: Checkout repository
        uses: actions/checkout@v4
      # docker login 
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # build the worker image 
      - name: Vote image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/vote-flask:latest -f vote/Dockerfile vote # the context ( the directory that the docker daemon will work on ) 
      - name: Pushing image to the hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/vote-flask:latest
        # Re-deploy ( rollout ) the updated image for the targeted deployment pods 
      - name: Vote deployment rollout 
        run: kubectl rollout restart deployment ${{ vars.VOTE_DEPLOYMENT_NAME }} -n ${{ vars.FRONTEND_NAMESPACE }}
          
            











      
