name: Worker CI
on:
  pull_request:
    branches:
      - main
    paths:
      - "worker/**/*.csproj"
      - "worker/**/*.cs"
      - "worker/Dockerfile"
jobs:
  worker-build-push-ci:
    runs-on: ubuntu-latest

    steps:
      # host runner repo clone 
      - name: Checkout repository
        uses: actions/checkout@v4
      # docker login 
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # build the worker image 
      - name: Worker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/worker-net:latest -f worker/Dockerfile worker # the context ( the directory that the docker daemon will work on ) 
      - name: Pushing image to the hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/worker-net:latest
          
            











      
